name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  iac-scan:
    name: Infrastructure Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          soft_fail: true

  sast-scan:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=devsecops-app
            -Dsonar.organization=susovandas19
        continue-on-error: true

  k8s-policy-check:
    name: Kubernetes Policy Enforcement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: instrumenta/conftest-action@master
        with:
          files: k8s/deployment.yaml
          policy: policy/k8s.rego

  build-and-container-scan:
    name: Image Build & Vulnerability Scan
    needs: [iac-scan, sast-scan, k8s-policy-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devsecops-app:${{ github.sha }} -f app/Dockerfile app/
      - uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/devsecops-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
      - run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag ${{ secrets.DOCKER_USERNAME }}/devsecops-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/devsecops-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/devsecops-app:latest

  deploy:
    name: Azure Kubernetes Deployment
    needs: build-and-container-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Inject Non-Secret Variables into K8s Manifest
        run: |
          sed -i "s/DOCKER_USERNAME_PLACEHOLDER/${{ secrets.DOCKER_USERNAME }}/g" k8s/deployment.yaml
          sed -i "s/DB_HOST_PLACEHOLDER/${{ secrets.DB_HOST }}/g" k8s/deployment.yaml
          sed -i "s/DB_USER_PLACEHOLDER/${{ secrets.DB_USER }}/g" k8s/deployment.yaml
          sed -i "s|AWS_S3_BUCKET_PLACEHOLDER|${{ secrets.AWS_S3_BUCKET }}|g" k8s/deployment.yaml
          sed -i "s|AWS_ACCESS_KEY_ID_PLACEHOLDER|${{ secrets.AWS_ACCESS_KEY_ID }}|g" k8s/deployment.yaml
      - name: Login via Az module
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get Secrets from Azure Key Vault
        uses: Azure/get-keyvault-secrets@v1
        id: akvSecrets
        with:
          keyvault: "devsecops-vault-12345"
          secrets: 'db-password, aws-secret-key'
      - name: Copy K8s Files to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "k8s/"
          target: "/home/azureuser/"
      - name: Execute Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          envs: db-password, aws-secret-key
          script: |
            kubectl create secret generic devsecops-secrets \
              --from-literal=db-password=${{ steps.akvSecrets.outputs.db-password }} \
              --from-literal=aws-secret-key=${{ steps.akvSecrets.outputs.aws-secret-key }} \
              --dry-run=client -o yaml | kubectl apply -f -
            
            kubectl apply -f /home/azureuser/k8s/deployment.yaml
            kubectl rollout restart deployment devsecops-app

  dast-scan:
    name: OWASP ZAP DAST Scan
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'http://${{ secrets.AZURE_VM_IP }}:30080'
          fail_action: false
          token: ${{ secrets.ZAP_GITHUB_TOKEN }}
          allow_issue_writing: true

    name: Upload ZAP artifact
    uses: actions/upload-artifact@v4
    with:
     name: zapscan
     path: |
      report_html.html
      report_json.json
      report_md.md
